CREATE TABLE IF NOT EXISTS account (
  id BIGSERIAL PRIMARY KEY,
  name TEXT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  photo_path TEXT,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS artist (
  id BIGINT REFERENCES account (id) ON DELETE CASCADE UNIQUE NOT NULL,
  artist_name TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS beat (
  id BIGSERIAL PRIMARY KEY,
  artist_id BIGINT REFERENCES artist (id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  bpm TEXT NOT NULL,
  key TEXT NOT NULL,
  photo_path TEXT NOT NULL,
  mp3_path TEXT NOT NULL,
  wav_path TEXT,
  likes BIGINT DEFAULT 0,
  genre TEXT DEFAULT 'All',
  mood TEXT DEFAULT 'All',
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tag (
  id BIGSERIAL PRIMARY KEY,
  beat_id BIGINT REFERENCES beat (id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS price (
  id BIGSERIAL PRIMARY KEY,
  beat_id BIGINT REFERENCES beat (id) ON DELETE CASCADE UNIQUE NOT NULL,
  standart_price TEXT NOT NULL,
  premium_price TEXT,
  unlimited_price TEXT
);

CREATE TABLE IF NOT EXISTS account_beat (
  id BIGSERIAL PRIMARY KEY,
  account_id BIGINT REFERENCES account (id) ON DELETE CASCADE NOT NULL,
  beat_id BIGINT REFERENCES beat (id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS playlist (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS playlist_beat (
  playlist_id BIGINT REFERENCES playlist (id) ON DELETE CASCADE NOT NULL,
  beat_id BIGINT REFERENCES beat (id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (playlist_id, beat_id)
);

CREATE TABLE IF NOT EXISTS account_playlist (
  account_id BIGINT REFERENCES account (id) ON DELETE CASCADE NOT NULL,
  playlist_id BIGINT REFERENCES playlist (id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (playlist_id, account_id)
);