CREATE TABLE user (
  id BIGSERIAL,
  name TEXT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  photo_path TEXT,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE artist (
  id BIGINT UNIQUE NOT NULL,
  artist_name TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE beat (
  id BIGSERIAL,
  artist_id BIGINT REFERENCES artist (id) NOT NULL ON DELETE CASCADE,
  name TEXT NOT NULL,
  bpm TEXT NOT NULL,
  key TEXT NOT NULL,
  photo_path TEXT NOT NULL,
  mp3_path TEXT NOT NULL,
  wav_path TEXT,
  like INT DEFAULT(0),
  genre TEXT DEFAULT("All"),
  mood TEXT DEFAULT("All"),
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE tag (
  id BIGSERIAL,
  beat_id BIGINT REFERENCES beat (id) NOT NULL ON DELETE CASCADE,
  name TEXT NOT NULL
);

CREATE TABLE price (
  id BIGSERIAL,
  beat_id BIGINT REFERENCES beat (id) UNIQUE NOT NULL ON DELETE CASCADE,
  standart_price TEXT NOT NULL,
  premium_price TEXT,
  unlimited_price TEXT
);

CREATE TABLE users_bought_beat (
  id BIGSERIAL,
  user_id BIGINT REFERENCES user (id) NOT NULL ON DELETE CASCADE,
  beat_id BIGINT REFERENCES beat (id) NOT NULL ON DELETE CASCADE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE users_playlist (
  id BIGSERIAL,
  user_id BIGINT REFERENCES user (id) NOT NULL ON DELETE CASCADE,
  beat_id BIGINT REFERENCES beat (id) NOT NULL ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);